defmodule WithDecimalWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :with_decimal

  # Serves the OpenAPI document generated by Portolan.
  plug Plug.Static, at: "/", from: :with_decimal, only: ~w(openapi.json)

  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.Parsers,
    parsers: [:urlencoded, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug WithDecimalWeb.Router
end
