defmodule Portolan.Controller do
  @moduledoc """
  Adds a Phoenix controller to the documented API.

      defmodule MyAppWeb.UserController do
        use MyAppWeb, :controller
        use Portolan.Controller

        @typedoc "Identifies a user."
        @type show_params :: %{required(:id) => Ecto.UUID.t()}

        @doc "Fetches a user."
        @spec show(Plug.Conn.t(), show_params()) :: {:ok, User.t()} | {:error, :not_found}
        def show(_conn, %{id: id}), do: Accounts.fetch_user(id)
      end

  `use Portolan.Controller` must come after `use Phoenix.Controller`, as
  it replaces its `action/2`.

  Only the controllers using this module are documented, so HTML
  controllers and internal endpoints stay out of the OpenAPI document.
  Every routed action must have a `@doc` and a `@spec`, actions with
  `@doc false` are left out.

  ## Runtime

  The `action/2` function of the controller is replaced, so every action:

  1. receives its parameters cast into the type of its spec, with atom
     keys and typed values. When they cannot be cast, the action is not
     called and the client gets a `422` response with the errors
  2. can return its result instead of a connection, see
     `Portolan.Response` for the supported results

  Actions receiving `map()` get the parameters as Phoenix gives them, and
  actions returning a connection keep working as usual.

  Parameters are cast with the contracts generated by the Portolan
  compiler, see `Portolan.Contracts`. In development, add `:portolan` to
  the `:reloadable_compilers` of the endpoint, so the contracts are
  updated when the code is reloaded:

      config :my_app, MyAppWeb.Endpoint,
        reloadable_compilers: [:elixir, :app, :portolan]

  """

  alias Portolan.Cast
  alias Portolan.Contracts
  alias Portolan.Response

  @doc false
  defmacro __using__(_opts) do
    quote do
      unless Module.overridable?(__MODULE__, {:action, 2}) do
        raise CompileError,
          file: __ENV__.file,
          line: __ENV__.line,
          description: "use Portolan.Controller after use Phoenix.Controller"
      end

      @portolan_app Mix.Project.config()[:app]

      @doc false
      @spec __portolan__() :: :controller
      def __portolan__, do: :controller

      # Replaces the overridable action/2 of Phoenix.Controller.
      @doc false
      @spec action(Plug.Conn.t(), term()) :: Plug.Conn.t()
      def action(conn, _opts), do: Portolan.Controller.dispatch(conn, __MODULE__, @portolan_app)
    end
  end

  @doc """
  Returns whether `module` is a controller documented by Portolan.

  ## Examples

      iex> Portolan.Controller.documented?(String)
      false

  """
  @spec documented?(module()) :: boolean()
  def documented?(module) do
    Code.ensure_loaded?(module) and function_exported?(module, :__portolan__, 0)
  end

  @doc """
  Calls the current action of `controller` with its parameters cast, and
  sends the response for its result.

  This is the `action/2` of the controllers using this module. `app` is
  the application whose contracts describe the controller.
  """
  @spec dispatch(Plug.Conn.t(), module(), atom()) :: Plug.Conn.t()
  def dispatch(conn, controller, app) do
    action = Phoenix.Controller.action_name(conn)

    case params(conn.params, controller, action, app) do
      {:ok, params} -> Response.render(conn, apply(controller, action, [conn, params]))
      {:error, errors} -> Response.invalid_params(conn, errors)
    end
  end

  defp params(params, controller, action, app) do
    contracts = contracts!(controller, app)

    case Contracts.params(contracts, controller, action) do
      {:ok, :undocumented} -> {:ok, params}
      {:ok, type} -> Cast.cast(type, params, resolve: Contracts.resolve(contracts))
      :error -> {:ok, params}
    end
  end

  defp contracts!(controller, app) do
    case Contracts.fetch(app) do
      {:ok, contracts} ->
        if Contracts.stale?(contracts, controller), do: reload!(controller, app), else: contracts

      {:error, reason} ->
        missing!(app, reason)
    end
  end

  # The controller was recompiled, the contracts may have been too.
  defp reload!(controller, app) do
    case Contracts.reload(app) do
      {:ok, contracts} ->
        if Contracts.stale?(contracts, controller) do
          raise "the Portolan contracts of #{inspect(controller)} are outdated. " <>
                  "Run mix compile, and add :portolan to the :reloadable_compilers of the " <>
                  "endpoint to update them when the code is reloaded"
        end

        contracts

      {:error, reason} ->
        missing!(app, reason)
    end
  end

  @spec missing!(atom(), term()) :: no_return()
  defp missing!(app, reason) do
    raise "cannot read the Portolan contracts of #{inspect(app)} (#{inspect(reason)}). " <>
            "Add :portolan to the compilers in mix.exs: compilers: Mix.compilers() ++ [:portolan]"
  end
end
