defmodule Portolan.UI do
  @moduledoc """
  Renders an HTML page showing the OpenAPI document.

  The page loads one of these interfaces from the jsDelivr CDN:

  * `:scalar` - [Scalar](https://scalar.com), MIT license
  * `:swagger_ui` - [Swagger UI](https://swagger.io/tools/swagger-ui/),
    Apache 2.0 license

  Versions are pinned and loaded with
  [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity),
  so the browser refuses any file different from the one Portolan was
  released with.

  The page is generated by the Portolan compiler next to the document, so
  it is served as a static file and no code of Portolan runs to show it.
  As the interface is loaded from the CDN, the browser needs access to it
  and the Content Security Policy of the application, if any, must allow
  `https://cdn.jsdelivr.net`.
  """

  @scalar %{
    script:
      "https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.73.0/dist/browser/standalone.js",
    integrity: "sha384-OKyMdsDX84ypSZEhVun8YElXk5c2GQaH3EXPOc6ItmVcLDUAvKHYwvDLvAgsqVtB"
  }

  @swagger_ui %{
    script: "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.33.1/swagger-ui-bundle.js",
    integrity: "sha384-ZPehFMQommnnuaZ4rpxgkgTT2DKFVp4hZC/7pLit+9Lek9T1YGSo23eHFbvNkXkw",
    style: "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.33.1/swagger-ui.css",
    style_integrity: "sha384-Ov4/wv3j2bmct8cDc5X4ngJZohVPzEmc6uDPH8WeljUxO5vtoykvMEfbu9Vh6RaW"
  }

  @typedoc """
  An available interface.
  """
  @type ui :: :scalar | :swagger_ui

  @typedoc """
  Options for `render/2`.

  * `:title` - the title of the page
  * `:url` - the URL of the OpenAPI document, relative to the page
  """
  @type option :: {:title, String.t()} | {:url, String.t()}

  @doc """
  The available interfaces.

  ## Examples

      iex> Portolan.UI.uis()
      [:scalar, :swagger_ui]

  """
  @spec uis() :: [ui(), ...]
  def uis, do: [:scalar, :swagger_ui]

  @doc """
  Renders the page of the interface `ui`.
  """
  @spec render(ui(), [option()]) :: String.t()
  def render(ui, opts) do
    title = opts |> Keyword.fetch!(:title) |> escape()
    url = Keyword.fetch!(opts, :url)

    """
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>#{title}</title>
    #{head(ui)}  </head>
      <body>
    #{body(ui, url)}  </body>
    </html>
    """
  end

  defp head(:scalar), do: ""

  defp head(:swagger_ui) do
    ~s(    <link rel="stylesheet" href="#{@swagger_ui.style}" integrity="#{@swagger_ui.style_integrity}" crossorigin="anonymous">\n)
  end

  defp body(:scalar, url) do
    """
        <div id="app"></div>
        #{script(@scalar)}
        <script>Scalar.createApiReference("#app", #{js(%{"url" => url})})</script>
    """
  end

  defp body(:swagger_ui, url) do
    """
        <div id="swagger-ui"></div>
        #{script(@swagger_ui)}
        <script>SwaggerUIBundle(#{js(%{"dom_id" => "#swagger-ui", "url" => url})})</script>
    """
  end

  defp script(%{script: src, integrity: integrity}),
    do: ~s(<script src="#{src}" integrity="#{integrity}" crossorigin="anonymous"></script>)

  # JSON is valid JavaScript. Slashes are escaped so no value can close the
  # script element.
  defp js(map), do: map |> JSON.encode!() |> String.replace("</", "<\\/")

  defp escape(text), do: text |> Plug.HTML.html_escape() |> IO.iodata_to_binary()
end
