defmodule Portolan.UI do
  @moduledoc """
  Renders an HTML page showing the OpenAPI document.

  The page loads one of these interfaces from the jsDelivr CDN:

  * `:scalar` - [Scalar](https://scalar.com), MIT license
  * `:swagger_ui` - [Swagger UI](https://swagger.io/tools/swagger-ui/),
    Apache 2.0 license

  Versions are pinned and loaded with
  [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity),
  so the browser refuses any file different from the one Portolan was
  released with.

  The page is generated by the Portolan compiler next to the document, so
  it is served as a static file and no code of Portolan runs to show it.

  When the interface is loaded from the CDN, the browser needs access to
  it and the Content Security Policy of the application, if any, must
  allow `https://cdn.jsdelivr.net`. To serve the interface from the
  application instead, install a copy of its files with
  `mix portolan.ui.install`.
  """

  @assets %{
    scalar: [
      %{
        kind: :script,
        name: "scalar",
        file: "scalar-1.73.0.js",
        url:
          "https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.73.0/dist/browser/standalone.js",
        integrity: "sha384-OKyMdsDX84ypSZEhVun8YElXk5c2GQaH3EXPOc6ItmVcLDUAvKHYwvDLvAgsqVtB"
      }
    ],
    swagger_ui: [
      %{
        kind: :style,
        name: "swagger-ui",
        file: "swagger-ui-5.33.1.css",
        url: "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.33.1/swagger-ui.css",
        integrity: "sha384-Ov4/wv3j2bmct8cDc5X4ngJZohVPzEmc6uDPH8WeljUxO5vtoykvMEfbu9Vh6RaW"
      },
      %{
        kind: :script,
        name: "swagger-ui",
        file: "swagger-ui-5.33.1.js",
        url: "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.33.1/swagger-ui-bundle.js",
        integrity: "sha384-ZPehFMQommnnuaZ4rpxgkgTT2DKFVp4hZC/7pLit+9Lek9T1YGSo23eHFbvNkXkw"
      }
    ]
  }

  @typedoc """
  An available interface.
  """
  @type ui :: :scalar | :swagger_ui

  @typedoc """
  A file of an interface.

  * `kind` - `:script` or `:style`
  * `name` - the name shared by every version of the file
  * `file` - the name of the local copy, including the version
  * `url` - where the file is in the CDN
  * `integrity` - the subresource integrity of the file
  """
  @type asset :: %{
          kind: :script | :style,
          name: String.t(),
          file: String.t(),
          url: String.t(),
          integrity: String.t()
        }

  @typedoc """
  A function downloading a URL.
  """
  @type fetch_fun :: (String.t() -> {:ok, binary()} | {:error, term()})

  @typedoc """
  Options for `render/2`.

  * `:title` - the title of the page
  * `:url` - the URL of the OpenAPI document, relative to the page
  * `:assets` - `:cdn` (default) to load the interface from the CDN, or
    `{:local, path}` to load the copies installed in `path`, relative to
    the page
  """
  @type option ::
          {:title, String.t()} | {:url, String.t()} | {:assets, :cdn | {:local, String.t()}}

  @doc """
  The available interfaces.

  ## Examples

      iex> Portolan.UI.uis()
      [:scalar, :swagger_ui]

  """
  @spec uis() :: [ui(), ...]
  def uis, do: [:scalar, :swagger_ui]

  @doc """
  The files of the interface `ui`.
  """
  @spec assets(ui()) :: [asset(), ...]
  def assets(ui), do: Map.fetch!(@assets, ui)

  @doc """
  Renders the page of the interface `ui`.
  """
  @spec render(ui(), [option()]) :: String.t()
  def render(ui, opts) do
    title = opts |> Keyword.fetch!(:title) |> escape()
    url = Keyword.fetch!(opts, :url)
    {styles, scripts} = ui |> assets() |> Enum.split_with(&(&1.kind == :style))
    location = Keyword.get(opts, :assets, :cdn)

    """
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>#{title}</title>
    #{Enum.map_join(styles, &"    #{tag(&1, location)}\n")}  </head>
      <body>
        <div id="#{element(ui)}"></div>
    #{Enum.map_join(scripts, &"    #{tag(&1, location)}\n")}    <script>#{init(ui, url)}</script>
      </body>
    </html>
    """
  end

  @doc """
  The configuration given to Scalar, besides the URL of the document.

  Telemetry and the AI features of Scalar are disabled, as they send data
  to the services of Scalar. Developer tools are shown only on localhost,
  and the document can be downloaded as JSON, as it is generated.

  ## Examples

      iex> Portolan.UI.scalar_config()["telemetry"]
      false

  """
  @spec scalar_config() :: %{String.t() => term()}
  def scalar_config do
    %{
      "telemetry" => false,
      "agent" => %{"disabled" => true},
      "mcp" => %{"disabled" => true},
      "showDeveloperTools" => "localhost",
      "documentDownloadType" => "json"
    }
  end

  @doc """
  Lists the files of the interface `ui` that are not installed in `dir`.
  """
  @spec missing(ui(), Path.t()) :: [String.t()]
  def missing(ui, dir) do
    for asset <- assets(ui), not File.regular?(Path.join(dir, asset.file)), do: asset.file
  end

  @doc """
  Installs the files of the interface `ui` in `dir`, see `install_assets/3`.
  """
  @spec install(ui(), Path.t(), fetch_fun()) :: {:ok, [Path.t()]} | {:error, String.t()}
  def install(ui, dir, fetch), do: install_assets(assets(ui), dir, fetch)

  @doc """
  Downloads `assets` with `fetch` and saves them in `dir`.

  Nothing is saved unless every file matches its integrity. Files of other
  versions of the same assets are removed.
  """
  @spec install_assets([asset()], Path.t(), fetch_fun()) ::
          {:ok, [Path.t()]} | {:error, String.t()}
  def install_assets(assets, dir, fetch) do
    downloads = Enum.map(assets, &download(&1, fetch))

    case for({:error, message} <- downloads, do: message) do
      [] ->
        File.mkdir_p!(dir)
        {:ok, for({:ok, asset, content} <- downloads, do: save(asset, content, dir))}

      messages ->
        {:error, Enum.join(messages, "\n")}
    end
  end

  defp save(asset, content, dir) do
    remove_other_versions(asset, dir)
    path = Path.join(dir, asset.file)
    File.write!(path, content)
    path
  end

  defp download(asset, fetch) do
    case fetch.(asset.url) do
      {:ok, content} ->
        if integrity(content) == asset.integrity,
          do: {:ok, asset, content},
          else: {:error, "the integrity of #{asset.url} does not match, it was not saved"}

      {:error, reason} ->
        {:error, "cannot download #{asset.url}: #{format_reason(reason)}"}
    end
  end

  defp remove_other_versions(asset, dir) do
    extension = Path.extname(asset.file)

    dir
    |> Path.join("#{asset.name}-*#{extension}")
    |> Path.wildcard()
    |> Enum.reject(&(Path.basename(&1) == asset.file))
    |> Enum.each(&File.rm!/1)
  end

  defp integrity(content), do: "sha384-" <> Base.encode64(:crypto.hash(:sha384, content))

  defp format_reason(reason) when is_binary(reason), do: reason
  defp format_reason(reason), do: inspect(reason)

  defp element(:scalar), do: "app"
  defp element(:swagger_ui), do: "swagger-ui"

  defp init(:scalar, url),
    do: ~s[Scalar.createApiReference("#app", #{js(Map.put(scalar_config(), "url", url))})]

  defp init(:swagger_ui, url),
    do: "SwaggerUIBundle(#{js(%{"dom_id" => "#swagger-ui", "url" => url})})"

  defp tag(%{kind: :script} = asset, location),
    do:
      ~s(<script src="#{src(asset, location)}" integrity="#{asset.integrity}"#{cors(location)}></script>)

  defp tag(%{kind: :style} = asset, location),
    do:
      ~s(<link rel="stylesheet" href="#{src(asset, location)}" integrity="#{asset.integrity}"#{cors(location)}>)

  defp src(asset, :cdn), do: asset.url
  defp src(asset, {:local, path}), do: Path.join(path, asset.file)

  defp cors(:cdn), do: ~s( crossorigin="anonymous")
  defp cors({:local, _path}), do: ""

  # JSON is valid JavaScript. Slashes are escaped so no value can close the
  # script element.
  defp js(map), do: map |> JSON.encode!() |> String.replace("</", "<\\/")

  defp escape(text), do: text |> Plug.HTML.html_escape() |> IO.iodata_to_binary()
end
