defmodule MinimalWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :minimal

  # Serves the OpenAPI document and its interface, generated by Portolan.
  plug Plug.Static, at: "/", from: :minimal, only: ~w(openapi.json openapi.html)

  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.Parsers,
    parsers: [:urlencoded, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug MinimalWeb.Router
end
